# Generated by Django 4.1.1 on 2022-09-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complejidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
