version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.envs/.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    depends_on:
      - db
    build:
      context: ./broker # The path in the machine that have the files, in this case root
      dockerfile: Dockerfile # The name of the Dockerfile definition
      
  web:
    build: .
    command: python3.10 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.envs/.postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    pgdata: