# Generated by Django 2.2.28 on 2022-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=255, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(max_length=255, null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
    ]
